import { useEffect, useState } from 'react';
import { Box, Typography, Button, Snackbar, Alert } from '@mui/material';
import { DataGrid, type GridColDef } from '@mui/x-data-grid';
import { CheckCircle } from '@mui/icons-material';
import { fetchFields, submitMusterLog } from '../../features/muster/api/musterApi';
import type { Field } from '../../features/muster/model/muster';

export const MorningMusterPage = () => {
    const [fields, setFields] = useState<Field[]>([]);
    const [loading, setLoading] = useState(true);
    const [auditLog, setAuditLog] = useState<{ id: string, fieldNo: string, workers: number, status: string, fullField: Field }[]>([]);
    const [message, setMessage] = useState<string | null>(null);

    useEffect(() => {
        loadFields();
    }, []);

    const loadFields = async () => {
        try {
            const data = await fetchFields();
            setFields(data);

            // Transform fields into muster rows for the UI (Mocking some values for now)
            const initialLog = data.map((f: Field) => ({
                id: f.fieldId, // Using Field ID as Row ID
                fieldNo: f.fieldNo,
                workers: 0, // Default to 0, to be filled by officer
                status: 'Pending',
                fullField: f
            }));
            setAuditLog(initialLog);
        } catch (error) {
            console.error('Error loading fields:', error);
        } finally {
            setLoading(false);
        }
    };

    const processRowUpdate = (newRow: any) => {
        const updatedRow = { ...newRow, workers: Number(newRow.workers) || 0, status: (Number(newRow.workers) || 0) > 0 ? 'Logged' : 'Pending' };
        setAuditLog((prev) => prev.map((row) => (row.id === newRow.id ? updatedRow : row)));
        return updatedRow;
    };

    const handleSubmit = async () => {
        try {
            // 1. Validate we have a division context
            const divisionId = fields[0]?.division?.divisionId;
            if (!divisionId) {
                setMessage('Error: No Division linked to these fields. Cannot submit.');
                return;
            }

            // 2. Filter for active entries (where workers > 0)
            const activeEntries = auditLog.filter(row => row.workers > 0);

            if (activeEntries.length === 0) {
                setMessage('Please enter worker counts for at least one field.');
                return;
            }

            // 3. Prepare Payload
            // We aggregate all field entries into ONE Muster Log for the Division
            const attendancePayload = activeEntries.map(entry => ({
                fieldId: entry.id, // Field ID
                fieldNo: entry.fieldNo,
                count: entry.workers,
                role: 'General'
            }));

            await submitMusterLog({
                // musterId: Let backend generate it
                tenantId: '00000000-0000-0000-0000-000000000000',
                date: new Date().toISOString().split('T')[0],
                attendanceData: JSON.stringify(attendancePayload),
                isApproved: false,
                division: { divisionId: divisionId }
            });
            console.log('Submitting Payload:', {
                // musterId: Generated by backend
                tenantId: '00000000-0000-0000-0000-000000000000',
                date: new Date().toISOString().split('T')[0],
                attendanceData: JSON.stringify(attendancePayload),
                isApproved: false,
                division: { divisionId: divisionId }
            });

            setMessage('Muster Submitted Successfully!');
        } catch (error) {
            console.error(error);
            setMessage('Failed to submit muster. Backend Error.');
        }
    };

    const columns: GridColDef[] = [
        { field: 'fieldNo', headerName: 'Field No', width: 120, headerClassName: 'super-app-theme--header' },
        {
            field: 'workers',
            headerName: 'Worker Count (Click to Edit)',
            width: 250,
            editable: true,
            type: 'number',
            headerClassName: 'super-app-theme--header',
            cellClassName: 'editable-cell-highlight'
        },
        { field: 'status', headerName: 'Status', width: 150, headerClassName: 'super-app-theme--header' }
    ];

    return (
        <Box>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                <Box>
                    <Typography variant="h5" fontWeight="bold">Morning Muster</Typography>
                    <Typography variant="body2" color="text.secondary">Daily Headcount Entry</Typography>
                    <Box sx={{ display: 'flex', gap: 1, mt: 1 }}>
                        <Button
                            variant="contained"
                            size="small"
                            startIcon={<CheckCircle />}
                            onClick={handleSubmit}
                            sx={{ bgcolor: '#4CAF50', borderRadius: '20px', textTransform: 'none' }}
                        >
                            Submit Muster
                        </Button>
                    </Box>
                </Box>
            </Box>

            <Box sx={{ height: 400, width: '100%', bgcolor: 'white', border: '1px solid #ddd' }}>
                <DataGrid
                    rows={auditLog}
                    columns={columns}
                    processRowUpdate={processRowUpdate}
                    onProcessRowUpdateError={(error) => console.error(error)}
                    loading={loading}
                    hideFooter
                    sx={{
                        border: 'none',
                        '& .MuiDataGrid-columnHeaders': {
                            backgroundColor: '#E0E0E0',
                            fontWeight: 'bold',
                            borderBottom: '2px solid #999',
                        }
                    }}
                />
            </Box>

            <Snackbar open={!!message} autoHideDuration={3000} onClose={() => setMessage(null)}>
                <Alert severity={message?.includes('Success') ? 'success' : 'error'} sx={{ width: '100%' }}>{message}</Alert>
            </Snackbar>
        </Box>
    );
};
